### ISSUE TITLE
Add Git tags to generate releases

### ISSUE THREAD

**Issue by jetm** [archlinuxfr/aurvote#6]
Hello,

Is it possible to add Git tags to generate releases and they can be called from AUR to generate packages?

Thanks

**Comment by Skunnyk** [comment]
Yes, I'll add a tag an make a small release :)

**Comment by jetm** [comment]
@Skunnyk: Thanks, I have an aurvote PKGBUILD waiting to test it.

**Comment by jetm** [comment]
@Skunnyk: Still waiting for a Git tag for a release. :smiley:

**Comment by Skunnyk** [comment]
Woops, done :]
https://github.com/archlinuxfr/aurvote/releases

**Comment by jetm** [comment]
I have modified [aurvote AUR package](https://aur.archlinux.org/packages/aurvote/) and released with this tag.

Thanks!
