### ISSUE TITLE
aurvote failed behind a proxy

### ISSUE THREAD

**Issue by jetm** [archlinuxfr/aurvote#7]
Will aurvote support AUR web v4?

**Comment by Skunnyk** [comment]
Hi,

Hm, I don't use aurvote very often, but I just tried and it works on aur4. What is your problem ?

**Comment by jetm** [comment]
Hi @Skunnyk,

I just tried in a different network and you're right aurvote works. The another network has not proxy and looking in aurvote code it seems it lacks of proxy support.

I going to rename this issue. Hack later if adding proxy support solve my issue. I might need to send a pull request as well.

Thanks,
